// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atqjaiebixuzomrfwilu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cWphaWViaXh1em9tcmZ3aWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTkxOTcsImV4cCI6MjA3Mjc3NTE5N30.OGAQFsAl1Eo1tmPZ93VZoSL5tO2FYZa_szeRvUmoj-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Offline mode utilities (kept for backward compatibility, defaults to online)
export let isOfflineMode = false;

export interface OfflineSettings {
  supabaseUrl: string;
  supabaseKey: string;
  localUrl: string;
  localKey: string;
  cloudUrl: string;
}

export function getOfflineSettings(): OfflineSettings {
  try {
    const stored = localStorage.getItem('offline_supabase_settings');
    const parsed = stored ? JSON.parse(stored) : {};
    return {
      supabaseUrl: parsed.supabaseUrl || SUPABASE_URL,
      supabaseKey: parsed.supabaseKey || SUPABASE_PUBLISHABLE_KEY,
      localUrl: parsed.localUrl || 'http://localhost:54321',
      localKey: parsed.localKey || '',
      cloudUrl: parsed.cloudUrl || SUPABASE_URL,
    };
  } catch {
    return {
      supabaseUrl: SUPABASE_URL,
      supabaseKey: SUPABASE_PUBLISHABLE_KEY,
      localUrl: 'http://localhost:54321',
      localKey: '',
      cloudUrl: SUPABASE_URL,
    };
  }
}

export function setOfflineMode(enabled: boolean, localUrl?: string, localKey?: string) {
  isOfflineMode = enabled;
  const current = getOfflineSettings();
  const settings = {
    ...current,
    localUrl: localUrl || current.localUrl,
    localKey: localKey || current.localKey,
  };
  localStorage.setItem('offline_supabase_settings', JSON.stringify(settings));
}