// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atqjaiebixuzomrfwilu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cWphaWViaXh1em9tcmZ3aWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTkxOTcsImV4cCI6MjA3Mjc3NTE5N30.OGAQFsAl1Eo1tmPZ93VZoSL5tO2FYZa_szeRvUmoj-4";

// Check localStorage for offline mode settings
const getStoredMode = () => {
  try {
    return localStorage.getItem('db_mode') || 'online';
  } catch {
    return 'online';
  }
};

const getStoredLocalUrl = () => {
  try {
    return localStorage.getItem('db_local_url') || 'http://localhost:54321';
  } catch {
    return 'http://localhost:54321';
  }
};

const getStoredLocalKey = () => {
  try {
    return localStorage.getItem('db_local_key') || SUPABASE_PUBLISHABLE_KEY;
  } catch {
    return SUPABASE_PUBLISHABLE_KEY;
  }
};

// Determine active URL and key based on mode
const storedMode = getStoredMode();
const ACTIVE_URL = storedMode === 'offline' ? getStoredLocalUrl() : SUPABASE_URL;
const ACTIVE_KEY = storedMode === 'offline' ? getStoredLocalKey() : SUPABASE_PUBLISHABLE_KEY;

// Export mode status for use in UI
export const isOfflineMode = storedMode === 'offline';
export const currentDbUrl = ACTIVE_URL;
export const DB_MODE = storedMode as 'online' | 'offline';

// Helper functions to manage offline mode
export const setOfflineMode = (enabled: boolean, localUrl?: string, localKey?: string) => {
  try {
    localStorage.setItem('db_mode', enabled ? 'offline' : 'online');
    if (localUrl) localStorage.setItem('db_local_url', localUrl);
    if (localKey) localStorage.setItem('db_local_key', localKey);
    // Reload to apply changes
    window.location.reload();
  } catch (e) {
    console.error('Failed to set offline mode:', e);
  }
};

export const getOfflineSettings = () => ({
  mode: getStoredMode(),
  localUrl: getStoredLocalUrl(),
  localKey: getStoredLocalKey(),
  cloudUrl: SUPABASE_URL,
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(ACTIVE_URL, ACTIVE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
